services:
  proxy:
    image: dommin/starter-proxy:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - nginx

  nginx:
    image: dommin/starter-nginx:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_nginx
    command: sh -c "nginx -g \"daemon off;\""
    volumes:
      - ./public:/usr/src/public
    depends_on:
      - php

  php:
    image: dommin/starter-php:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_php
    volumes:
      - ./public:/usr/src/public
      - ./.env:/usr/src/.env:ro
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - ./.env
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: dommin/starter-mysql:${IMAGE_TAG}
    container_name: ${DOCKER_PREFIX}_mysql
    restart: unless-stopped
    healthcheck:
      test: mysql -h localhost -u root -p${DB_PASSWORD} -e 'SELECT version();'
      start_period: 5s
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
