version: '3.8'

services:
  nginx:
    image: dommin/starter-nginx:${IMAGE_TAG}
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html/public
    depends_on:
      - php

  php:
    image: dommin/starter-php:${IMAGE_TAG}
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false

  mysql:
    image: dommin/starter-mysql:${IMAGE_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
